### ISSUE TITLE
Buen trabajo

### ISSUE THREAD

**Issue by ElisaGDR** [4GeeksAcademy/Mercedes0708-Blog_Star_Wars#1]
Bien hecho @Mercedes0708 ! 
Muy buen trabajo: nombres de variables y funciones descriptivas, código limpio. 
Tip: Cuida más el tema de líneas vacias ;)

**Comment by Mercedes0708** [comment]
Muchas Gracias!!  @ElisaGDR !!
Me podrías explicar lo de las líneas  vacías??
Es que no se si lo dices por pocas o por muchas  😅 
De nuevo gracias.

**Comment by ElisaGDR** [comment]
Lo digo porque en algunos componentes pones muchas. Y hay que poner las necesarias. Por ejemplo: 

![image](https://github.com/4GeeksAcademy/Mercedes0708-Blog_Star_Wars/assets/135215841/451206a7-4fd1-4c67-8502-e6eefc2bf1e9)
Aquí sobra esa casi última línea vacía

![image](https://github.com/4GeeksAcademy/Mercedes0708-Blog_Star_Wars/assets/135215841/5c86957c-5a06-48e1-be10-08012a716f01)
Aquí sobra una de las tres líneas vacías que has dejado de separación (son siempre 2 tras las importaciones)

 ;)

**Comment by Mercedes0708** [comment]
Vale, muchas gracias !! 😀
